export * from "./About/About";
export * from "./Contact/Contact";
export * from "./Home/Home";
export * from "./Services/Services";
export * from "./Login/Login";
export * from "./Register/Register";
export * from "./ForgotPassword/ForgotPassword";
export * from "./profile/Profile";
export * from "./excerise planner/ExcerisePlanner";
export * from "./excerise planner/inputData/InputData";