export * from "./About/About";
export * from "./Contact/Contact";
export * from "./Home/Home";
export * from "./Services/Services";
export * from "./Login/Login";
export * from "./Register/Register";
export * from "./ForgotPassword/ForgotPassword";
export * from "./profile/Profile";
export * from "./excerise planner/ExcerisePlanner";
export * from "./Meal-suggestion/Mealsuggestion";
export * from "./consultant search/Consultant";
export * from "./vaccine/Vaccine";
export * from "./Medical Data/Medical";
export * from "./select user/UserSelection";