name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update npm
      run: npm install -g npm@latest

    - name: Install Dependencies (Frontend)
      run: npm ci
      working-directory: ../../frontend  # Adjust the path based on your project structure

    - name: Build (Frontend)
      run: npm run build --if-present
      working-directory: ../../frontend  # Adjust the path based on your project structure

    - name: Test (Frontend)
      run: npm test
      working-directory: ../../frontend  # Adjust the path based on your project structure

    - name: Deploy with gh-pages (Frontend)
      run: |
        git remote set-url origin https://github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ../../frontend  # Adjust the path based on your project structure
