name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update npm
      run: npm install -g npm@latest

    - name: Check Lock File
      run: ls -l frontend
      working-directory: frontend

    - name: Clear npm cache
      run: npm cache clean --force
      working-directory: frontend

    - name: Install Dependencies
      run: npm i
      working-directory: frontend

    - name: Build
      run: npm run build --if-present
      working-directory: frontend

    - name: Test
      run: npm test
      working-directory: frontend

    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: frontend
